### PR TITLE
Bring filecorgi to libp2p docs

### PR DESCRIPTION
**Pull request by yusefnapora**
Also sneaks in a fix to `make build` failing on an M1 Mac. It was downloading the 32-bit intel build of Hugo, which Rosetta can't translate.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/work/docs/docs/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/work/docs/docs/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-06-14T20_13_43_171Z-debug.log
```
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!
- No markdown files were changed, so no page checks were run!

**Review by JurbinM — APPROVED** [review]

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by DannyS03** [comment]
hi @yusefnapora, did we still want to include [filecorgi](https://github.com/filecorgi)?

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!
found div [<div id="body-inner">
<h1>Addressing</h1>
<p>Flexible networks require flexible addressing systems. Since libp2p is designed to work across a wide variety of networks, we need a way to work with a lot of different addressing schemes in a consistent way.</p>
<p>A <code>multiaddress</code> (often abbreviated <code>multiaddr</code>), is a convention for encoding multiple layers of addressing information into a single “future-proof” path structure. It [defines][spec_multiaddr] human-readable and machine-optimized encodings of common transport and overlay protocols and allows many layers of addressing to be combined and used together.</p>
<p>For example: <code>/ip4/127.0.0.1/udp/1234</code> encodes two protocols along with their essential addressing information. The <code>/ip4/127.0.0.1</code> informs us that we want the <code>127.0.0.1</code> loopback address of the IPv4 protocol, and <code>/udp/1234</code> tells us we want to send UDP packets to port <code>1234</code>.</p>
<p>Things get more interesting as we compose further. For example, the multiaddr <code>/p2p/QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N</code> uniquely identifies my local IPFS node, using libp2p’s <a href="https://github.com/multiformats/multiaddr/blob/master/protocols.csv">registered protocol id</a> <code>/p2p/</code> and the <a href="../../reference/glossary/#multihash">multihash</a> of my IPFS node’s public key.</p>
<div class="notices tip"><p>For more on peer identity and its relation to public key cryptography, see <a href="../peer-id/">Peer Identity</a>.</p>
</div>
<p>Let’s say that I have the peer id <code>QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N</code> as above, and my public ip is <code>7.7.7.7</code>. I start my libp2p application and listen for connections on TCP port <code>4242</code>.</p>
<p>Now I can start <a href="../../concepts/peer-routing/">handing out multiaddrs to all my friends</a>, of the form <code>/ip4/7.7.7.7/tcp/4242/p2p/QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N</code>. Combining my “location multiaddr” (my IP and port) with my “identity multiaddr” (my libp2p <code>PeerId</code>), produces a new multiaddr containing both key pieces of information.</p>
<p>Now not only do my friends know where to find me, anyone they give that address to can verify that the machine on the other side is really me, or at least, that they control the private key for my <code>PeerId</code>. They also know (by virtue of the <code>/p2p/</code> protocol id) that I’m likely to support common libp2p interactions like opening connections and negotiating what application protocols we can use to communicate. That’s not bad!</p>
<p>This can be extended to account for multiple layers of addressing and abstraction. For example, the <a href="../../concepts/circuit-relay/#relay-addresses">addresses used for circuit relay</a> combine transport addresses with multiple peer identities to form an address that describes a “relay circuit”:</p>
<h3 id="more-information">More information</h3>
<p>For more detail, see the <a href="https://github.com/libp2p/specs/blob/master/addressing/README.md">Addressing spec</a>.</p>
<footer class="footline">
</footer>
</div>]

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!
found div [<div id="body-inner">
<footer class="footline">
</footer>
</div>]

**Review by DannyS03 — APPROVED** [review]

**Pull request merged**
