### PR TITLE
remove contexts from libp2p.New

### PR DESCRIPTION
**Pull request by marten-seemann**

### CODE REVIEW

**Comment by johnnymatthews** [comment]
I ran through this tutorial on a completely clean MacOS installation. After installing Homebrew I installed Go using `brew install golang`. I then started following this tutorial though, but I ran into a couple of errors:

## No `libp2p/go-libp2p` package

I got an error saying I needed to add the `libp2p/go-libp2p` package after running `go build -o libp2p-node`:

```shell
go build

> main.go:7:2: no required module provides package github.com/libp2p/go-libp2p; to add it:
>         go get github.com/libp2p/go-libp2p
```

I added the package with:

```shell
go get github.com/libp2p/go-libp2p
```

This line should probably be added into the tutorial, or can we assume that readers will already have this package installed?

## Not enough arguments error

After adding the `libp2p/go-libp2p` package, I ran `go build -o libp2p-node` again and got this error:
But then I hit a new error:

```shell
go build -o libp2p-node

> # github.com/user/go-libp2p-tutorial
> ./main.go:4:2: imported and not used: "context"
> ./main.go:12:25: not enough arguments in call to libp2p.New
>         have ()
>         want (context.Context, ...config.Option)
```

I'm not able to move on with the tutorial from here.

**Review by johnnymatthews — CHANGES_REQUESTED** [review]
See comment https://github.com/libp2p/docs/pull/108#issuecomment-967330497

**Comment by marten-seemann** [comment]
So, looks like I read the bug report wrong. Sorry for the confusion.
The issue was not the `context.Context` here, but it's _probably_ that the `go get github.com/libp2p/go-libp2p` is missing.

This PR is only needed once we remove the `context.Context` from `libp2p.New`. We already did in `master`, but it hasn't been released yet. That will happen in the next libp2p release (which will ship very soon).

@johnnymatthews Could you have a look at https://github.com/libp2p/go-libp2p/issues/1234 and see if the `go get` fixes their problem?

**Comment by johnnymatthews** [comment]
> Could you have a look at libp2p/go-libp2p#1234 and see if the go get fixes their problem?

Ah, I'm not quite sure what to do here. I don't know enough about Go to understand the ask. Should I run the tutorial in this PR again, substituting a command for `go get`?

**Comment by marten-seemann** [comment]
> Should I run the tutorial in this PR again, substituting a command for go get?

Let's wait until go-libp2p v0.16 is released.

**Comment by GLAD-DE** [comment]
> > Should I run the tutorial in this PR again, substituting a command for go get?
> 
> Let's wait until go-libp2p v0.16 is released.

Are you able to give a timeframe on when 0.16 will be released?

**Comment by marten-seemann** [comment]
> Are you able to give a timeframe on when 0.16 will be released?

We were aiming for last week 😅

**Comment by marten-seemann** [comment]
@johnnymatthews go-libp2p v0.16.0 was released 2 weeks ago (and in fact, we just released v0.17.0). Can we get this PR landed now?

**Comment by johnnymatthews** [comment]
I got the _no libp2p package_ error again, [listed in my previous comment](https://github.com/libp2p/docs/pull/108#issuecomment-967330497). I can't make suggestions to this `.md` file for some reason.

I also get the following message when I run `go build -o libp2p-node`:

```shell
# github.com/user/go-libp2p-tutorial
./main.go:4:2: imported and not used: "context
```

Removing `"context"` from `main.go` and re-rerunning `go build -o libp2p-node` lets me build the project.

I was able to run through the rest of the tutorial fine.

**Comment by marten-seemann** [comment]
> This line should probably be added into the tutorial, or can we assume that readers will already have this package installed?

`go get github.com/libp2p/go-libp2p` is right. It has to be run in every repo, there's no concept of having this package installed globally.

**Comment by johnnymatthews** [comment]
Understood. As it stands right now then, before this tutorial is published we need to:

1. Remove the `context` import, as mentioned in https://github.com/libp2p/docs/pull/108#issuecomment-998047264
2. Add the `go get github.com/libp2p/go-libp2p` command to the top of the tutorial.

Again, I don't have edit rights on this repo, so I can't do anything unfortunately. Well actually, I guess I could make a fork and a PR.

**Comment by kunalgoyal9** [comment]
@johnnymatthews @marten-seemann I am still getting `ctx` not defined issue. I think we need to define context here.
image

**Pull request merged**
