### PR TITLE
chore: add alerts, make quote font size smaller

### PR DESCRIPTION
**Pull request by p-shahi**

### CODE REVIEW

**Comment by marten-seemann** [comment]
This applies to a lot more than just QUIC, the `>` exists on many pages. For example: https://docs.libp2p.io/concepts/transports/webtransport/

**Comment by marten-seemann** [comment]
This applies to a lot more than just QUIC, the `>` exists on many pages. For example: https://docs.libp2p.io/concepts/transports/webtransport/

**Comment by DannyS03** [comment]
I meant to update these!

**Comment by DannyS03** [comment]
Will open another PR @p-shahi and merge this into that.

**Comment by p-shahi** [comment]
@DannyS03  I've pushed changes, can you review. Don't think we need another pr

**Review by marten-seemann — APPROVED** [review]

**Comment by marten-seemann** [comment]
image

Font size could be +2px. Margins don't seem ideal (no margin-bottom, but lots of margin-top).

**Review by DannyS03 — APPROVED** [review]

**Comment by p-shahi** [comment]
@marten-seemann done
image

**Pull request merged**
