### PR TITLE
[META] General structure, flow, & content enhancements

### PR DESCRIPTION
**Pull request by DannyS03**
## Context

- Improve the overall content presentation and navigation of the docs.
- Adds sections and directories for current content.
- This PR will primarily include theme-level changes. Additional PRs will propose changes to populate and improve the various sections, as well as add/modify sub-sections where needed.
- This structure will be iterated on as we add content.

### Original proposed structure with chapter/book approach:

<details> 

```
 ┣ 1. Introduction
 ┃ ┣ 1.1. Network Basics
 ┃ ┃ ┣ 1.1.1. The Internet and the Permanent Web
 ┃ ┃ ┣ 1.1.2. Introduction to Computer Networks
 ┃ ┃ ┣ 1.1.3. Introduction to Distributed Computing
 ┃ ┃ ┣ 1.1.4. Introduction to Data Structures
 ┃ ┣ 1.2. libp2p
 ┃ ┃ ┣ 1.2.1 A Modular P2P Networking Stack
 ┣ 2. Core Components
 ┃ ┣ 2.0. Fundamentals
 ┃ ┃ ┣ 2.0.1. Overview
 ┃ ┃ ┣ 2.0.2. Addressing
 ┃ ┃ ┣ 2.0.3. Protocols
 ┃ ┃ ┣ ...
 ┃ ┃ ┣ ...
 ┃ ┃ ┣ 2.0.n. More
 ┃ ┣ 2.1. Transports
 ┃ ┃ ┣ 2.1.1. Overview
 ┃ ┃ ┣ 2.1.2. TCP
 ┃ ┃ ┣ 2.1.3. QUIC
 ┃ ┃ ┣ 2.1.4. WebSocket
 ┃ ┃ ┣ 2.1.5. WebTransport
 ┃ ┃ ┣ 2.1.6. WebRTC
 ┃ ┣ 2.2. Secure Communication
 ┃ ┃ ┣ 2.2.1. Overview
 ┃ ┃ ┣ 2.2.2. Noise
 ┃ ┃ ┣ 2.2.3. TLS
 ┃ ┣ 2.3. Stream Multiplexing
 ┃ ┃ ┣ 2.3.1. Overview
 ┃ ┃ ┣ 2.3.2. mplex
 ┃ ┃ ┣ 2.3.3. yamux
 ┃ ┣ 2.4. NAT Traversal
 ┃ ┃ ┣ 2.4.1. Overview
 ┃ ┃ ┣ 2.4.2. Circuit Relay
 ┃ ┃ ┣ 2.4.3. Hole Punching
 ┃ ┃ ┣ 2.4.4. AutoNAT
 ┃ ┃ ┣ 2.4.5. DCUtR
 ┃ ┣ 2.5. Discovery
 ┃ ┃ ┣ 2.5.1. Overview
 ┃ ┃ ┣ 2.5.2. mDNS
 ┃ ┃ ┣ 2.5.3. Random Walk
 ┃ ┃ ┣ 2.5.4. Rendezvous
 ┃ ┣ 2.6. Routing
 ┃ ┃ ┣ 2.6.1. Overview
 ┃ ┃ ┣ 2.6.2. Peer Identity
 ┃ ┃ ┣ 2.6.3. Peer Routing
 ┃ ┃ ┃ ┣ 2.6.3.1. DHT-based Peer Routing
 ┃ ┃ ┣ 2.6.4. Content Routing
 ┃ ┃ ┃ ┣ 2.6.4.1. DHT-based Peer Routing
 ┃ ┣ 2.7. Messaging
 ┃ ┃ ┣ 2.7.1. Overview
 ┃ ┃ ┣ 2.7.2. Publish/Subscribe
 ┃ ┣ 2.8. Data Exchange
 ┃ ┃ ┣ 2.8.1. Overview
 ┃ ┃ ┣ 2.8.2. Bitswap
 ┃ ┣ 2.9. Security Considerations
 ┃ ┃ ┣ 2.9.1. Overview
 ┃ ┣ 2.10. Miscellaneous
 ┃ ┃ ┣ 2.10.1. Glossary
 ┣ 3. Guides
 ┃ ┣ 3.1. Get Started
 ┃ ┃ ┣ 3.1.1. Install libp2p
 ┃ ┃ ┣ 3.1.2. Quick Start
 ┃ ┣ 3.2. Protocol Basics
 ┃ ┃ ┣ 3.2.1. Prerequisites
 ┃ ┃ ┣ 3.2.2. Transports
 ┃ ┃ ┣ 3.2.3. Secure Channels
 ┃ ┃ ┣ 3.2.4. Steam Muxers
 ┃ ┃ ┣ 3.2.5. Peer Discovery
 ┃ ┃ ┣ 3.2.6. NATs
 ┃ ┃ ┣ 3.2.7. Peer Routing
 ┃ ┃ ┣ 3.2.8. Content Routing
 ┃ ┃ ┣ 3.2.9. P2P Messaging
 ┃ ┃ ┣ 3.2.10. Data Exchange
 ┃ ┣ 3.3. Examples
 ┃ ┃ ┣ 3.3.1. Overview
 ┃ ┃ ┣ 3.3.2. Chat Application
 ┃ ┃ ┣ ...
 ┃ ┃ ┣ ...
 ┃ ┃ ┣ 3.3.n. Example
 ┣ 4. Reference
 ┃ ┣ 4.1. Overview
 ┃ ┣ ...
 ┃ ┣ ...
 ┃ ┣ 4.n. More
 ┣ 5. Community
 ┃ ┣ 4.1. Get Involved
 ┃ ┣ 4.2. How to Contribute
```

</details>

## Current restructure: latest preview

**Please view the latest Fleek preview [here](https://bafybeibqy35glvrdbnmhj6t2k66erc43dmhymeggbtsmezvrl6nfbc4bly.on.fleek.co/).**

### CODE REVIEW

**Comment by marten-seemann** [comment]
It would probably make sense to interchange WebTransprot and WebRTC.
 ┃ ┃ ┣ 2.1.4. WebSocket
 ┃ ┃ ┣ 2.1.5. WebTransport
 ┃ ┃ ┣ 2.1.6. WebRTC

Haven't looked at the rest of the structure yet, will do when this is not a draft any more.

**Comment by DannyS03** [comment]
Tagged the team for their input when they have the chance for an initial review

**Comment by marten-seemann** [comment]
There's a lot of changed files in this PR, not sure what exactly to review here. The proposed structure from the PR description?

**Comment by DannyS03** [comment]
> There's a lot of changed files in this PR, not sure what exactly to review here. The proposed structure from the PR description?

Right, best to view the changes on the Fleek previews. I've added the latest one in the [issue description](https://github.com/libp2p/docs/pull/186#issue-1364326150) at the bottom.

**Comment by p-shahi** [comment]
@DannyS03 I generally like the new structure but am apprehensive about merging this. This PR introduces multiple empty pages, enough that the empty ones outnumber the pages with content. wdyt about removing the empty pages?
For instance, in the Transports section, all but the Overview page are empty, so we could remove them but keep the reference to future content (TCP, QUIC, etc) in the top level Transports page.

**Review by p-shahi — CHANGES_REQUESTED** [review]
@DannyS03 I generally like the new structure but am apprehensive about merging this. This PR introduces multiple empty pages, enough that the empty ones outnumber the pages with content. wdyt about removing the empty pages?
For instance, in the Transports section, all but the Overview page are empty, so we could remove them but keep the reference to future content (TCP, QUIC, etc) in the top level Transports page.
Once content is written for different sections, they can be added to the appropriate place in subsequent prs. That way we can still commit to the structure you've defined without the final product looking so sparse

**Comment by DannyS03** [comment]
> @DannyS03 I generally like the new structure but am apprehensive about merging this. This PR introduces multiple empty pages, enough that the empty ones outnumber the pages with content. wdyt about removing the empty pages? For instance, in the Transports section, all but the Overview page are empty, so we could remove them but keep the reference to future content (TCP, QUIC, etc) in the top level Transports page. Once content is written for different sections, they can be added to the appropriate place in subsequent prs. That way we can still commit to the structure you've defined without the final product looking so sparse

thanks @p-shahi! Yes, that works. They are mainly there to be placeholders

**Comment by johnnymatthews** [comment]
I agree with @p-shahi here; there's lots of empty pages, so we shouldn't merge this as it stand. I also have some thoughts regarding the chapters and titles.

## Chapters

I'm generally against using chapters in docs sites. Docs sites are meant to be skimmed through, with readers finding the specific content they want. Adding chapters makes this whole site read much more like a book. I'd suggest removing the chapter numbers and just having the titles speak for themselves. 

## Titles

There's lots of repetition across the titles of some of these pages. For example:

Screen Shot 2022-09-22 at 10 44 50 AM

These pages are already under the *Introduction* section, so it's fair to assume that the reader will understand that these are _introductions to_ something. I recommend shortening the titles as much as you can.

**Comment by p-shahi** [comment]
@DannyS03 Thanks for removing the placeholder docs! Looks a lot better now.

> I'm generally against using chapters in docs sites. Docs sites are meant to be skimmed through, with readers finding the specific content they want. Adding chapters makes this whole site read much more like a book. I'd suggest removing the chapter numbers and just having the titles speak for themselves.

Hm, I noticed that we changed the site to "libp2p Book" too. This seems very intentional, was it discussed with others before this PR?
I'm not entirely opposed to this because the Rust docs are a good example of docs done in a book format: https://doc.rust-lang.org/book/title-page.html

But I just want to make sure everyone is ok going in this direction

**Comment by DannyS03** [comment]
Cheers @johnnymatthews @p-shahi

I’ve been considering a few things on how we can organize all the libp2p material. What seems like an interesting format to consider is eventually having something along the lines of the following:

- [book.libp2p.io](http://book.libp2p.io/) - more theoretical and conceptual - a public goods networking resource
- [guides.libp2p.io](http://guides.libp2p.io/) - how to guides, examples and tutorials (doesn’t need chapters)
- [implementations.libp2p.io](http://implementations.libp2p.io/) - implementations page

Part of this is because we end up doing a good amount of information curation as different implementations document certain components and implementation specific content lives in the repos of those implementations. Then, as an implementer, you'd eventually be interested in the actual libp2p specs that go into details. The concepts are generally timeless (or can be considered so), so I see the benefit in presenting them in a structured way

**Comment by DannyS03** [comment]
Note: merge conflicts will be resolved once structure and format is finalized.

**Comment by p-shahi** [comment]
> I’ve been considering a few things on how we can organize all the libp2p material. What seems like an interesting format to consider is eventually having something along the lines of the following:
> 
> [book.libp2p.io](http://book.libp2p.io/) - more theoretical and conceptual - a public goods networking resource
> [guides.libp2p.io](http://guides.libp2p.io/) - how to guides, examples and tutorials (doesn’t need chapters)
> [implementations.libp2p.io](http://implementations.libp2p.io/) - implementations page

I like this approach of separating content into book, guides, and implementations 👍 
I do have a question about the use of subdomains versus subdirectories. I think it makes sense to have subdomain for book (akin to docs.libp2p and later for blog.libp2p and spec.libp2p) but I don't fully understand why guides and implementations can't be subdirectories (in keeping with how implementation is a subdir today.)
Is this for consistency/organizing content, SEO, or something else?

Also is this in keeping with how docs.ipfs.tech plans to organize its content too? I'm not suggesting that we follow the same structure but would like to see how similar/divergent libp2p docs/guides will be vs ipfs docs/guides.

In the interest of getting moving this PR closer to being merged, I'll poke the other reviewers: @marten-seemann @mxinden @MarcoPolo what do you guys think of Danny's proposal here?

**Comment by marten-seemann** [comment]
> I do have a question about the use of subdomains versus subdirectories. I think it makes sense to have subdomain for book (akin to docs.libp2p and later for blog.libp2p and spec.libp2p) but I don't fully understand why guides and implementations can't be subdirectories (in keeping with how implementation is a subdir today.)

I agree.

> In the interest of getting moving this PR closer to being merged, I'll poke the other reviewers

I'm not actually sure what the proposal of _this PR_ is, and what a general proposal is. The fleek preview in the top comment doesn't work any more, so I also can't see what's going on. In the future, can we keep changes (more) atomic, e.g. change the theme in one PR, and modify the ToC in a separate PR? It would also help to have general discussions on issues, not on PRs (PRs would only _implement_ a decision that was reached in a discussion on an issue). That would make reviewing a lot easier.

**Comment by p-shahi** [comment]
> It would also help to have general discussions on issues, not on PRs (PRs would only implement a decision that was reached in a discussion on an issue). That would make reviewing a lot easier.

Yeah I agree with this and meant to suggest it earlier.
Danny can we schedule something this week (or early next) to present your vision of how you'd like to organize the docs page and the libp2p website in general? If you prefer to do it async, maybe you can record a [Loom video](https://www.loom.com/) (I think PL has support for this app.) Up to you.

**Comment by DannyS03** [comment]
> I do have a question about the use of subdomains versus subdirectories. I think it makes sense to have subdomain for book (akin to docs.libp2p and later for blog.libp2p and spec.libp2p) but I don't fully understand why guides and implementations can't be subdirectories (in keeping with how implementation is a subdir today.)
Is this for consistency/organizing content, SEO, or something else?

That is also what I had in mind, for guides and implementations to be subdirectories.

> Also is this in keeping with how docs.ipfs.tech plans to organize its content too? I'm not suggesting that we follow the same structure but would like to see how similar/divergent libp2p docs/guides will be vs ipfs docs/guides.

I'm not sure it would be, but it is something to consider. Right now, the libp2p docs aren't in line with the IPFS docs on the theme level, and not necessarily in line with the content flow.

> I'm not actually sure what the proposal of this PR is, and what a general proposal is. The fleek preview in the top comment doesn't work any more, so I also can't see what's going on. In the future, can we keep changes (more) atomic, e.g. change the theme in one PR, and modify the ToC in a separate PR? It would also help to have general discussions on issues, not on PRs (PRs would only implement a decision that was reached in a discussion on an issue). That would make reviewing a lot easier.

Indeed, we can keep changes more atomic and can lay out potential changes in an issue. 

The purpose of the PR is to update the structure (and flow) of the current libp2p docs. For this PR:
- the theme itself remains the same (Hugo learn theme) and uses the learn theme's configuration to apply changes to presentation. 
- because chapters are being proposed, I included them end-to-end in one PR as I thought splitting up these changes wasn't reasonable since some sections would have chapters while others wouldn't.

The fleek preview looks good on my end, I am just pulling it from the latest build. [Here is the one](https://bafybeiff3baq5esl4pthmd7onet7g6dve6prtyipnuachclbl7vplhmfum.on.fleek.co/) for `881ddae`.

**Comment by DannyS03** [comment]
> > It would also help to have general discussions on issues, not on PRs (PRs would only implement a decision that was reached in a discussion on an issue). That would make reviewing a lot easier.
> 
> Yeah I agree with this and meant to suggest it earlier. Danny can we schedule something this week (or early next) with the team to present your vision of how you'd like to organize the docs page and the libp2p website in general? If you prefer to do it async, maybe you can record a [Loom video](https://www.loom.com/) (I think PL has support for this app.) Up to you.

That'd be good - I'll try with Loom first considering that there changes already proposed and share a link, where we can follow up synchronously if needed.

**Comment by jennijuju** [comment]
created #203 for future discussion

**Comment by DannyS03** [comment]
@p-shahi I readded loom recording (not sure what happened to the original but I rerecorded a new one).

**Comment by DannyS03** [comment]
Feel free to drop additional comments and concerns when you've had the chance to review the recording

**Review by p-shahi — APPROVED** [review]
these changes lgtm.

I think we should use this opportunity to give the DoS Mitigation page higher visibility and move it out of Reference. It can live either as its own section, or under Security Considerations. My preference is for the former.
We can keep the old page under Reference and link to the new location to not break any links we've shared.

**Review by marten-seemann — COMMENTED** [review]
I'm not sure I understand the purpose of this PR. It seems to make the document structure significantly worse than what we have today, adds a lot of empty / stub pages, and introduces formatting that's inconsistent with the rest of the site.

1. Why is this called a "book" now? Doesn't make a lot of sense to me, we're not planning to print this any time soon. "Documentation portal" seems to capture much better what we're doing here.
2. It seems like the [Introduction](https://docs.libp2p.io/introduction/) was removed and replaced with a not very helpful "Network Basics" site, which is empty.
4. Core Concepts > Introduction. Why do we have another Introduction section here, we already have a top-level Introduction.
5. all other sections: should we have sub-pages here, instead of dumping all the content onto an "Overview" page?

**Comment by DannyS03** [comment]
Looking at this again, I'm also proposing to remove the reference section as it does not serve much purpose (dos mitigation was moved out, the section on monitoring only references the dos mitigation guide, the overview is outdated and more of a filler, and the specs doc just references the specs). It can be revisited in the near future, but for now it seems to be redundant. The content in the overview was moved to the index file of the core components section and simply references the implementations page and the specs repo.

**Comment by DannyS03** [comment]
Also changed "Introduction" under "Core components" to "Fundamentals". To be clear, the intent is to open a variety of issues to track the next phase of updates to this structure, mainly being to populate what's missing and modularize the overviews (+ add new material as we progress).

**Comment by p-shahi** [comment]
@DannyS03 thanks for the additional changes. Couple of things to address now imo

1. Let's get rid of Miscellaneous and promote Glossary as a main section.
2. Keep the Reference section with the DoS, Monitoring, and Spec underneath it. Even though the spec section only links to the repo it's important to keep it, having it under Reference makes sense. For the DoS one, we've shared links to that page with other teams. Until we set up a url redirect, I don't want to move this yet. 

Can address in a follow up PR (or this same one, your preference):
1. Update the Overview for Reference
2. Each transport in the Transports page merits it's own subsection
3. Imo would be a nice QoL improvement if there was a Table of Contents in each section & subsection. Provides an immediate preview of doc and a means jump to a section.
4. Move Monitoring Your Application to its own subsection under DoS Mitigation. I think the new structure allows for what might have been the original intent with this page: https://docs.libp2p.io/reference/monitoring/ which to have a dedicated page for how to monitor libp2p 

Also @DannyS03, I'm not sold on the "Overview" pages as a means of organizing content. I like it less the more I navigate the site since it requires an additional click to navigate into the real content. I think it could be replaced by adding a ToC to the main section page with the content underneath.

**Comment by DannyS03** [comment]
@p-shahi @marten-seemann thanks again! Based on the feedback, I decided it's best to simplify the restructure approach here and work off of the current "portal" we have, where we can soon decide on how we'd like to "generally revamp" the libp2p site, docs, etc - I feel there is consensus to do so. We're preparing a proposal on different approaches we can take that I'll share next week.

For now, here are highlights of the recent changes:
- The changes categorize concepts based on components (but without chapter numbers) and create directories.
  - Uses index files to capture the overview/summary of the component, then lists a ToC for the specific components related to the general component on the index file (e.g. with Transports - there is a doc for dialing & listening, then for QUIC and WebTransport).
  - Added placeholders back for secure channels (this will be updated relatively soon).
  - The categories (or previously, chapters) that did not have content and acted as placeholders, I removed.
  - The categories with only "one main overview", are not a directories and are displayed as they originally were.
  - Glossary page is displayed as is
- Reference section added back.
  > Would note @p-shahi that I had added a redirect when we moved DoS to "Core Components", so if we'd like to reconsider the visibility again, we can do it in this PR.
- Descriptions updated for all page. but they are not thought-through. This is something I'll update once we decide on the structure as it would be worth having a similar tone and follow a standard on how we refer to different parts of the docs (i.e. sections vs. categories. vs. directories vs. something else.)
  > Hugo will autogenerate content summaries with a default summaryLength of 70, but renders as regular text [on purpose] (the ones we have right now aren't good because of this), so we are now using the "summary" property available in the front matter.
- Added additional visibility for specs to the footer under the GitHub reference.

**Review by p-shahi — APPROVED** [review]
> Based on the feedback, I decided it's best to simplify the restructure approach here and work off of the current "portal" we have, where we can soon decide on how we'd like to "generally revamp" the libp2p site, docs, etc - I feel there is consensus to do so. We're preparing a proposal on different approaches we can take that I'll share next week.

Ok sounds good.

> The changes categorize concepts based on components (but without chapter numbers) and create directories (or sections).

I do like book/chapter style organization. I found that Aleo organizes their docs similarly: https://developer.aleo.org/overview (without numbering.)

> Uses index files to capture the overview/summary of the component, then lists a ToC for the specific components related to the general component on the index file (e.g. with Transports - there is a doc for dialing & listening, then for QUIC and WebTransport).
The categories with only "one main overview", are not a directories and are displayed as they originally were.

👍

> Reference section added back.
Would note @p-shahi that I had added a redirect when we moved DoS to "Core Components", so if we'd like to reconsider the visibility again, we can do it in this PR.

Yes, let's promote DoS to be under Core Components in this PR.
I meant that we should also keep a DoS page (with a link to Core Components>DoS) under Reference only if there was no redirect. Since you had added a redirect, it can be removed from under Reference. Sorry if there was confusion from my end.

> Descriptions updated for all page. but they are not thought-through. This is something I'll update once we decide on the structure as it would be worth having a similar tone and follow a standard on how we refer to different parts of the docs (i.e. sections vs. categories. vs. directories vs. something else.)

👍

**Comment by DannyS03** [comment]
@marten-seemann [these changes](https://github.com/libp2p/docs/pull/186#issuecomment-1279595865) should make things more straight forward and great if you can provide a final review.

**Comment by DannyS03** [comment]
Upon merging this, I'll open PRs for AutoNAT, Noise, TLS, and will update yamux, mplex. 

Regarding QUIC:
We currently mention QUIC on the stream multiplexing article, and this PR now creates a subsection for QUIC under stream multiplexing as it does with the other protocols and core components, but perhaps this is not needed and QUIC should only be _explained_ under transports. I was thinking to add an overview on QUIC's "native stream multiplexing" under stream multiplexing, but in doing so, that would push us to add QUIC under secure channels (which may overlap with the TLS piece). I am in favor of this latter approach, and future diagrams would be valuable.

**Comment by p-shahi** [comment]
If no qualms, let's merge this by tomorrow e.o.d.

> I was thinking to add an overview on QUIC's "native stream multiplexing" under stream multiplexing, but in doing so, that would push us to add QUIC under secure channels (which may overlap with the TLS piece). I am in favor of this latter approach, and future diagrams would be valuable.

makes sense to me.

**Comment by DannyS03** [comment]
checking with @marten-seemann for any qualms.

**Comment by DannyS03** [comment]
🛳️?

**Comment by p-shahi** [comment]
## 🚢 it 🚀

**Pull request merged**
